#!/usr/bin/env python3
"""
Mesh Extraction Tab - Convert 3D Gaussian Splatting to GLB Meshes

This tab provides a unified interface for extracting meshes from 3DGS representations
generated by any source (Lyra, SHARP, external tools).

Supported Methods:
- Poisson Reconstruction: Standard surface reconstruction from point clouds
- TSDF Fusion: Fast depth-based reconstruction (lower quality, very fast)

The mesh extraction runs on RunPod serverless for GPU-accelerated processing.
"""

import gradio as gr
from pathlib import Path
from typing import List


def scan_for_ply_files() -> List[str]:
    """
    Scan output directories for available PLY files.
    Returns list of paths sorted by modification time (newest first).
    """
    ply_files = []
    
    # Directories to scan
    search_dirs = [
        Path("/srv/searidge_share/outputs/lyra"),
        Path("/srv/searidge_share/outputs/sharp"),
        Path("/srv/searidge_share/outputs/gen3c"),
        Path("/srv/searidge_share/outputs"),
    ]
    
    for search_dir in search_dirs:
        if search_dir.exists():
            # Find all .ply files recursively
            for ply_file in search_dir.rglob("*.ply"):
                try:
                    # Get file info
                    stat = ply_file.stat()
                    size_mb = stat.st_size / (1024 * 1024)
                    
                    # Skip very small files (likely not 3DGS)
                    if size_mb > 1:
                        ply_files.append((str(ply_file), stat.st_mtime, size_mb))
                except Exception:
                    continue
    
    # Sort by modification time (newest first) and deduplicate
    seen = set()
    unique_files = []
    for path, mtime, size in sorted(ply_files, key=lambda x: -x[1]):
        if path not in seen:
            seen.add(path)
            unique_files.append((path, size))
    
    # Return just the paths, with size info in display
    return [f"{path} ({size:.1f} MB)" for path, size in unique_files[:20]]  # Limit to 20 most recent

# =============================================================================
# CONSTANTS
# =============================================================================

MESH_DEFAULT_OUTPUT_DIR = "/srv/searidge_share/outputs/mesh"
MESH_DEFAULT_ENDPOINT_ID = ""  # User must configure

# Quality presets for mesh extraction
MESH_QUALITY_PRESETS = [
    "High Poly (1M vertices, detailed)",
    "Low Poly (200k vertices, fast)",
    "Custom",
]

# Export formats
EXPORT_FORMATS = [
    "GLB (Universal)",
    "OBJ + MTL (Textured)",
    "PLY (Point Cloud Fallback)",
]


def create_mesh_extraction_tab(
    default_endpoint_id: str = "",
    default_api_key: str = "",
) -> dict:
    """
    Create the Mesh Extraction tab UI components.
    
    Args:
        default_endpoint_id: Default RunPod endpoint ID (from saved config)
        default_api_key: Default RunPod API key (from saved config)
    
    Returns:
        Dictionary of Gradio components for event wiring.
    """
    components = {}
    
    # Check if we have saved credentials
    _has_creds = bool(default_endpoint_id and default_api_key)
    
    with gr.Tab("🔷 Mesh Extraction"):
        gr.Markdown("""
        ## 3DGS → Mesh Conversion
        
        Convert 3D Gaussian Splatting outputs to editable mesh formats (GLB, OBJ).
        Works with PLY files from **Lyra**, **SHARP**, or any standard 3DGS source.
        
        **Method:** Poisson Surface Reconstruction
        - Extracts point positions and colors from 3DGS
        - Estimates surface normals
        - Reconstructs watertight mesh with vertex colors
        - Exports as GLB for universal compatibility
        """)
        
        # =================================================================
        # INPUT SECTION
        # =================================================================
        with gr.Group():
            gr.Markdown("### 📥 Input")
            
            # Scan for available PLY files
            initial_ply_files = scan_for_ply_files()
            
            with gr.Row():
                components["ply_dropdown"] = gr.Dropdown(
                    choices=initial_ply_files,
                    label="Select PLY File",
                    info="Recent PLY files from Lyra, SHARP, and other outputs",
                    scale=3,
                    allow_custom_value=True,  # Allow pasting custom paths
                )
                components["refresh_btn"] = gr.Button("🔄 Refresh", scale=1)
            
            with gr.Row():
                components["input_ply"] = gr.Textbox(
                    label="Or Enter Path Manually",
                    placeholder="/srv/searidge_share/outputs/lyra/my_model.ply",
                    info="Paste a path here if not in the dropdown",
                    scale=3,
                )
            
            with gr.Row():
                components["input_format"] = gr.Radio(
                    choices=[
                        "Auto-detect",
                        "Lyra (PyTorch tensor)",
                        "Standard 3DGS",
                        "SHARP",
                    ],
                    value="Auto-detect",
                    label="Input Format",
                    info="Format of the input PLY file",
                )
        
        # =================================================================
        # POISSON RECONSTRUCTION SETTINGS
        # =================================================================
        with gr.Accordion("⚙️ Reconstruction Settings", open=True) as components["sugar_settings"]:
            gr.Markdown("""
            **Poisson Surface Reconstruction** creates a watertight mesh from the 3DGS point cloud.
            Colors are transferred from the Gaussian splats to mesh vertices.
            """)
            
            with gr.Row():
                components["quality_preset"] = gr.Dropdown(
                    choices=MESH_QUALITY_PRESETS,
                    value="High Poly (1M vertices, detailed)",
                    label="Quality Preset",
                    info="Target vertex count for the output mesh",
                )
            
            with gr.Row():
                components["poisson_depth"] = gr.Slider(
                    minimum=6,
                    maximum=12,
                    value=10,
                    step=1,
                    label="Poisson Depth",
                    info="Higher = more detail, but slower. Reduce (7-8) if you see bumpy artifacts.",
                )
                components["decimate_faces"] = gr.Number(
                    value=0,
                    label="Decimate to (faces)",
                    info="0 = no decimation. Set a target face count to reduce mesh size.",
                )
            
            # Hidden components to maintain compatibility with backend
            components["method"] = gr.Textbox(value="SuGaR (High Quality)", visible=False)
            components["regularization"] = gr.Textbox(value="dn_consistency (Best Quality)", visible=False)
            components["export_texture"] = gr.Checkbox(value=False, visible=False)
            components["texture_resolution"] = gr.Textbox(value="2048", visible=False)
            components["refinement_time"] = gr.Textbox(value="short (2k iter)", visible=False)
        
        # Hidden TSDF components (not currently used)
        components["tsdf_settings"] = gr.Accordion("TSDF Settings", visible=False)
        components["tsdf_voxel_size"] = gr.Slider(value=0.01, visible=False)
        components["tsdf_num_views"] = gr.Slider(value=32, visible=False)
        
        # =================================================================
        # OUTPUT SETTINGS
        # =================================================================
        with gr.Group():
            gr.Markdown("### 📤 Output")
            
            with gr.Row():
                components["output_name"] = gr.Textbox(
                    label="Output Name",
                    value="mesh_output",
                    placeholder="my_mesh",
                    scale=2,
                )
                components["output_format"] = gr.Dropdown(
                    choices=EXPORT_FORMATS,
                    value="GLB (Universal)",
                    label="Export Format",
                    scale=1,
                )
            
            with gr.Row():
                components["output_dir"] = gr.Textbox(
                    label="Output Directory",
                    value=MESH_DEFAULT_OUTPUT_DIR,
                    placeholder="/path/to/output",
                )
        
        # =================================================================
        # RUNPOD CREDENTIALS
        # =================================================================
        with gr.Accordion("🔑 RunPod Credentials", open=not _has_creds) as components["creds_accordion"]:
            gr.Markdown("""
            Mesh extraction runs on RunPod serverless. Uses the **GEN3C endpoint**.
            """)
            
            with gr.Row():
                components["edit_creds_btn"] = gr.Button("✏️ Edit Credentials", size="sm")
                components["test_creds_btn"] = gr.Button("🔍 Test Connection", size="sm")
            
            with gr.Group(visible=not _has_creds) as components["creds_group"]:
                with gr.Row():
                    components["endpoint_id"] = gr.Textbox(
                        label="Endpoint ID",
                        placeholder="abc123xyz",
                        value=default_endpoint_id,
                    )
                    components["api_key"] = gr.Textbox(
                        label="API Key",
                        placeholder="rp_xxxxxxxx",
                        value=default_api_key,
                        type="password",
                    )
                
                with gr.Row():
                    components["save_creds_btn"] = gr.Button("💾 Save Credentials", size="sm")
            
            components["creds_status"] = gr.Textbox(
                label="Status",
                interactive=False,
                max_lines=2,
            )
        
        # =================================================================
        # ACTION BUTTONS
        # =================================================================
        with gr.Row():
            components["extract_btn"] = gr.Button(
                "🔷 Extract Mesh",
                variant="primary",
                scale=2,
            )
            components["cancel_btn"] = gr.Button(
                "⏹️ Cancel",
                variant="stop",
                scale=1,
            )
        
        # =================================================================
        # OUTPUT DISPLAY
        # =================================================================
        with gr.Group():
            gr.Markdown("### 📊 Results")
            
            with gr.Row():
                components["output_path"] = gr.Textbox(
                    label="Output File Path",
                    interactive=False,
                    scale=2,
                )
                components["open_folder_btn"] = gr.Button("📂 Open Folder", scale=1)
            
            with gr.Row():
                components["logs"] = gr.Textbox(
                    label="Logs",
                    lines=10,
                    max_lines=20,
                    interactive=False,
                )
            
            with gr.Row():
                components["status"] = gr.Textbox(
                    label="Status",
                    interactive=False,
                    max_lines=2,
                )
        
        # =================================================================
        # BLENDER INTEGRATION
        # =================================================================
        with gr.Accordion("🎨 Blender Integration", open=False):
            gr.Markdown("""
            After mesh extraction, you can import the result into Blender for
            further editing, animation, or rendering.
            """)
            
            with gr.Row():
                components["blender_mesh_path"] = gr.Textbox(
                    label="Mesh Path for Blender",
                    placeholder="Auto-filled after extraction",
                    interactive=False,
                    scale=2,
                )
            
            with gr.Row():
                components["open_in_blender_btn"] = gr.Button(
                    "🎨 Open in Blender",
                    variant="secondary",
                )
                components["generate_blender_script_btn"] = gr.Button(
                    "📜 Generate Import Script",
                    variant="secondary",
                )
            
            components["blender_status"] = gr.Textbox(
                label="Blender Status",
                interactive=False,
                max_lines=2,
            )
        
        # =================================================================
        # HELP SECTION
        # =================================================================
        with gr.Accordion("❓ Help & Tips", open=False):
            gr.Markdown("""
            ## How It Works
            
            ### Poisson Surface Reconstruction
            
            This method converts 3D Gaussian Splatting point clouds to meshes:
            
            1. **Extract Points**: Reads positions and colors from 3DGS PLY
            2. **Estimate Normals**: Computes surface normals for each point
            3. **Poisson Reconstruction**: Creates watertight mesh surface
            4. **Color Transfer**: Maps original colors to mesh vertices
            5. **Cleanup & Export**: Removes artifacts, exports as GLB
            
            **Output:** Vertex-colored GLB mesh (universal format)
            
            ---
            
            ## Troubleshooting
            
            **Holes in mesh?**
            - Try lower Poisson depth (7-8)
            - Input may have sparse regions
            
            **Bumpy/noisy surface?**
            - Reduce Poisson depth from 10 to 7-8
            - Input may have outlier points
            
            **Missing colors?**
            - Colors are transferred as vertex colors
            - Some viewers may not display vertex colors by default
            - In Blender: Set viewport to "Material Preview" mode
            
            ---
            
            ## Input Format Notes
            
            - **Lyra**: Outputs PyTorch tensor format, auto-converted
            - **SHARP**: Standard 3DGS format, works directly
            - **External**: Most 3DGS viewers export compatible PLY
            
            ---
            
            ## Limitations
            
            - **No UV textures**: Output uses vertex colors, not UV-mapped textures
            - **Point cloud quality**: Mesh quality depends on input point density
            - **Large files**: High-poly meshes may be slow to load in viewers
            """)
    
    return components

