#!/usr/bin/env python3
"""
Mesh Cleanup Script for ArkRunr Pipeline

Cleans up meshes generated by Hunyuan3D or similar single-image-to-3D models.
Addresses common issues:
- Floating artifacts / disconnected components
- Non-manifold geometry
- Excessive triangle count
- Inconsistent normals

Usage:
    python cleanup_mesh.py input.glb output.glb
    python cleanup_mesh.py input.glb output.glb --target-triangles 100000
    python cleanup_mesh.py input.glb output.glb --aggressive
"""

import argparse
import sys
from pathlib import Path
from typing import Optional, Dict, Any

# Check for trimesh
try:
    import trimesh
    import numpy as np
    TRIMESH_AVAILABLE = True
except ImportError:
    TRIMESH_AVAILABLE = False
    print("Warning: trimesh not installed. Install with: pip install trimesh")


def cleanup_mesh(
    input_path: str,
    output_path: str,
    target_triangles: int = 150000,
    remove_small_components: bool = True,
    min_component_ratio: float = 0.01,
    fix_normals: bool = True,
    fill_holes: bool = False,
    smooth_iterations: int = 1,
    aggressive: bool = False,
) -> Dict[str, Any]:
    """
    Clean up a mesh for use in Unity/ArkRunr.
    
    Args:
        input_path: Path to input mesh (GLB, OBJ, etc.)
        output_path: Path to save cleaned mesh
        target_triangles: Target triangle count for decimation (0 = no decimation)
        remove_small_components: Remove small disconnected parts
        min_component_ratio: Minimum ratio of faces for a component to be kept
        fix_normals: Recompute and fix normals
        fill_holes: Attempt to fill holes (can be aggressive)
        smooth_iterations: Number of Laplacian smoothing passes
        aggressive: Enable aggressive cleanup (more decimation, hole filling)
    
    Returns:
        Dictionary with cleanup statistics
    """
    if not TRIMESH_AVAILABLE:
        raise ImportError("trimesh is required. Install with: pip install trimesh")
    
    print(f"[Cleanup] Loading: {input_path}")
    
    # Load mesh - handle GLB/GLTF scenes
    loaded = trimesh.load(input_path)
    
    # Handle scenes (GLB files often contain multiple meshes)
    if isinstance(loaded, trimesh.Scene):
        print(f"[Cleanup] Scene with {len(loaded.geometry)} geometries")
        # Combine all meshes into one
        meshes = []
        for name, geom in loaded.geometry.items():
            if isinstance(geom, trimesh.Trimesh):
                meshes.append(geom)
                print(f"  - {name}: {len(geom.faces)} faces")
        
        if not meshes:
            raise ValueError("No valid meshes found in scene")
        
        if len(meshes) == 1:
            mesh = meshes[0]
        else:
            mesh = trimesh.util.concatenate(meshes)
            print(f"[Cleanup] Combined into single mesh: {len(mesh.faces)} faces")
    else:
        mesh = loaded
    
    stats = {
        "input_file": input_path,
        "output_file": output_path,
        "input_vertices": len(mesh.vertices),
        "input_triangles": len(mesh.faces),
        "components_removed": 0,
        "operations": [],
    }
    
    print(f"[Cleanup] Input: {stats['input_vertices']:,} vertices, {stats['input_triangles']:,} triangles")
    
    # Aggressive mode adjustments
    if aggressive:
        target_triangles = min(target_triangles, 100000)
        min_component_ratio = 0.02
        fill_holes = True
        smooth_iterations = max(smooth_iterations, 2)
        print("[Cleanup] Aggressive mode enabled")
    
    # Step 1: Remove small disconnected components
    if remove_small_components:
        print("[Cleanup] Step 1: Removing small components...")
        try:
            # Split into connected components
            components = mesh.split(only_watertight=False)
            
            if len(components) > 1:
                print(f"  Found {len(components)} components")
                
                # Calculate minimum face count
                min_faces = len(mesh.faces) * min_component_ratio
                
                # Keep only large components
                large_components = [c for c in components if len(c.faces) > min_faces]
                
                if large_components:
                    stats["components_removed"] = len(components) - len(large_components)
                    mesh = trimesh.util.concatenate(large_components)
                    print(f"  Kept {len(large_components)} components, removed {stats['components_removed']}")
                    stats["operations"].append(f"Removed {stats['components_removed']} small components")
                else:
                    # Keep largest if all are small
                    mesh = max(components, key=lambda c: len(c.faces))
                    stats["components_removed"] = len(components) - 1
                    print(f"  Kept largest component only")
            else:
                print("  Single component, no removal needed")
        except Exception as e:
            print(f"  Warning: Component removal failed: {e}")
    
    # Step 2: Fix normals
    if fix_normals:
        print("[Cleanup] Step 2: Fixing normals...")
        try:
            mesh.fix_normals()
            stats["operations"].append("Fixed normals")
            print("  Normals fixed")
        except Exception as e:
            print(f"  Warning: Normal fixing failed: {e}")
    
    # Step 3: Fill holes (optional, can be aggressive)
    if fill_holes:
        print("[Cleanup] Step 3: Filling holes...")
        try:
            # trimesh's fill_holes can be aggressive
            mesh.fill_holes()
            stats["operations"].append("Filled holes")
            print("  Holes filled")
        except Exception as e:
            print(f"  Warning: Hole filling failed: {e}")
    
    # Step 4: Smooth (gentle Laplacian smoothing)
    if smooth_iterations > 0:
        print(f"[Cleanup] Step 4: Smoothing ({smooth_iterations} iterations)...")
        try:
            trimesh.smoothing.filter_laplacian(mesh, iterations=smooth_iterations)
            stats["operations"].append(f"Smoothed ({smooth_iterations} iterations)")
            print(f"  Applied {smooth_iterations} smoothing passes")
        except Exception as e:
            print(f"  Warning: Smoothing failed: {e}")
    
    # Step 5: Decimate if needed
    if target_triangles > 0 and len(mesh.faces) > target_triangles:
        print(f"[Cleanup] Step 5: Decimating {len(mesh.faces):,} → {target_triangles:,} triangles...")
        try:
            # Calculate reduction ratio (0-1, where 0.9 means reduce to 10%)
            reduction = 1.0 - (target_triangles / len(mesh.faces))
            reduction = max(0.01, min(0.99, reduction))  # Clamp to valid range
            
            # Try fast_simplification first (much faster)
            try:
                import fast_simplification
                simplified_vertices, simplified_faces = fast_simplification.simplify(
                    mesh.vertices, mesh.faces, target_reduction=reduction
                )
                mesh = trimesh.Trimesh(vertices=simplified_vertices, faces=simplified_faces)
                print(f"  Decimated to {len(mesh.faces):,} triangles (fast_simplification)")
            except ImportError:
                # Fall back to trimesh's built-in (slower)
                mesh = mesh.simplify_quadric_decimation(target_triangles)
                print(f"  Decimated to {len(mesh.faces):,} triangles (quadric)")
            
            stats["operations"].append(f"Decimated to {len(mesh.faces):,} triangles")
        except Exception as e:
            print(f"  Warning: Decimation failed: {e}")
    
    # Final stats
    stats["output_vertices"] = len(mesh.vertices)
    stats["output_triangles"] = len(mesh.faces)
    stats["is_watertight"] = mesh.is_watertight
    stats["is_winding_consistent"] = mesh.is_winding_consistent
    
    # Step 6: Export
    print(f"[Cleanup] Saving: {output_path}")
    
    # Determine format from extension
    output_ext = Path(output_path).suffix.lower()
    
    if output_ext == ".glb":
        # Export as GLB (binary glTF)
        mesh.export(output_path, file_type="glb")
    elif output_ext == ".gltf":
        mesh.export(output_path, file_type="gltf")
    elif output_ext == ".obj":
        mesh.export(output_path, file_type="obj")
    elif output_ext == ".ply":
        mesh.export(output_path, file_type="ply")
    elif output_ext == ".stl":
        mesh.export(output_path, file_type="stl")
    else:
        # Default to GLB
        mesh.export(output_path, file_type="glb")
    
    print(f"\n[Cleanup] Complete!")
    print(f"  Input:  {stats['input_triangles']:,} triangles")
    print(f"  Output: {stats['output_triangles']:,} triangles")
    print(f"  Reduction: {100 * (1 - stats['output_triangles'] / stats['input_triangles']):.1f}%")
    print(f"  Watertight: {stats['is_watertight']}")
    print(f"  Consistent winding: {stats['is_winding_consistent']}")
    
    return stats


def analyze_mesh(input_path: str) -> Dict[str, Any]:
    """
    Analyze a mesh without modifying it.
    
    Returns statistics and potential issues.
    """
    if not TRIMESH_AVAILABLE:
        raise ImportError("trimesh is required")
    
    print(f"[Analyze] Loading: {input_path}")
    
    loaded = trimesh.load(input_path)
    
    # Handle scenes
    if isinstance(loaded, trimesh.Scene):
        meshes = [g for g in loaded.geometry.values() if isinstance(g, trimesh.Trimesh)]
        if len(meshes) == 1:
            mesh = meshes[0]
        else:
            mesh = trimesh.util.concatenate(meshes)
    else:
        mesh = loaded
    
    # Compute stats
    components = mesh.split(only_watertight=False)
    
    bounds = mesh.bounds
    size = bounds[1] - bounds[0]
    
    stats = {
        "file": input_path,
        "vertices": len(mesh.vertices),
        "triangles": len(mesh.faces),
        "components": len(components),
        "is_watertight": mesh.is_watertight,
        "is_winding_consistent": mesh.is_winding_consistent,
        "bounds_min": bounds[0].tolist(),
        "bounds_max": bounds[1].tolist(),
        "size": size.tolist(),
        "center": mesh.centroid.tolist(),
    }
    
    # Identify issues
    issues = []
    
    if len(components) > 1:
        small_components = sum(1 for c in components if len(c.faces) < len(mesh.faces) * 0.01)
        if small_components > 0:
            issues.append(f"{small_components} small floating components (artifacts)")
    
    if not mesh.is_watertight:
        issues.append("Mesh has holes (not watertight)")
    
    if not mesh.is_winding_consistent:
        issues.append("Inconsistent face winding (normal issues)")
    
    if len(mesh.faces) > 500000:
        issues.append(f"High triangle count ({len(mesh.faces):,}) - may need decimation")
    
    stats["issues"] = issues
    
    print(f"\n[Analyze] Results:")
    print(f"  Vertices: {stats['vertices']:,}")
    print(f"  Triangles: {stats['triangles']:,}")
    print(f"  Components: {stats['components']}")
    print(f"  Size: {size[0]:.2f} x {size[1]:.2f} x {size[2]:.2f}")
    print(f"  Watertight: {stats['is_watertight']}")
    print(f"  Consistent winding: {stats['is_winding_consistent']}")
    
    if issues:
        print(f"\n  ⚠️ Issues found:")
        for issue in issues:
            print(f"    - {issue}")
    else:
        print(f"\n  ✅ No issues found")
    
    return stats


def main():
    parser = argparse.ArgumentParser(
        description="Clean up meshes for ArkRunr/Unity",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Basic cleanup
  python cleanup_mesh.py input.glb output.glb
  
  # Analyze without modifying
  python cleanup_mesh.py input.glb --analyze
  
  # Aggressive cleanup for problematic meshes
  python cleanup_mesh.py input.glb output.glb --aggressive
  
  # Custom settings
  python cleanup_mesh.py input.glb output.glb --target-triangles 100000 --smooth 2
  
  # Export to different format
  python cleanup_mesh.py input.glb output.obj
"""
    )
    
    parser.add_argument("input", help="Input mesh file (GLB, OBJ, PLY, etc.)")
    parser.add_argument("output", nargs="?", help="Output mesh file (optional for --analyze)")
    
    parser.add_argument("--analyze", action="store_true",
                        help="Analyze mesh without modifying")
    
    parser.add_argument("--target-triangles", type=int, default=150000,
                        help="Target triangle count (0 = no decimation, default: 150000)")
    
    parser.add_argument("--aggressive", action="store_true",
                        help="Aggressive cleanup (more decimation, hole filling)")
    
    parser.add_argument("--no-remove-components", action="store_true",
                        help="Don't remove small disconnected components")
    
    parser.add_argument("--no-fix-normals", action="store_true",
                        help="Don't fix normals")
    
    parser.add_argument("--fill-holes", action="store_true",
                        help="Fill holes in mesh")
    
    parser.add_argument("--smooth", type=int, default=1,
                        help="Smoothing iterations (0 = none, default: 1)")
    
    parser.add_argument("--min-component-ratio", type=float, default=0.01,
                        help="Minimum component size ratio (default: 0.01 = 1%%)")
    
    args = parser.parse_args()
    
    if not TRIMESH_AVAILABLE:
        print("Error: trimesh is required. Install with: pip install trimesh")
        sys.exit(1)
    
    input_path = Path(args.input)
    
    if not input_path.exists():
        print(f"Error: Input file not found: {input_path}")
        sys.exit(1)
    
    if args.analyze:
        analyze_mesh(str(input_path))
        return
    
    if not args.output:
        # Default output name
        output_path = input_path.with_stem(input_path.stem + "_cleaned")
    else:
        output_path = Path(args.output)
    
    cleanup_mesh(
        str(input_path),
        str(output_path),
        target_triangles=args.target_triangles,
        remove_small_components=not args.no_remove_components,
        min_component_ratio=args.min_component_ratio,
        fix_normals=not args.no_fix_normals,
        fill_holes=args.fill_holes,
        smooth_iterations=args.smooth,
        aggressive=args.aggressive,
    )


if __name__ == "__main__":
    main()

